Rearrage order

diff --git a/run/autostart-alley.template b/run/autostart-alley.template
--- a/run/autostart-alley.template
+++ b/run/autostart-alley.template
@@ -45,17 +45,6 @@ echo "SUCCESS"
 
 echo "Environment started"
 
-echo -e "\nStarting Kelly..."
-/opt/kelly/bin/kelly start
-sleep 10
-K=`/opt/kelly/bin/kelly ping`
-if [[ $K != 'pong' ]]; then
-    echo $K
-    echo "FAILED"
-    exit 1
-fi
-echo "SUCCESS"
-
 echo -e "\nStarting Funnel..."
 /opt/funnel/bin/funnel start
 sleep 10
@@ -90,6 +79,17 @@ if [[ -x /opt/mm_srv/bin/mm_srv ]]; then
     fi
     echo "SUCCESS"
 fi
+
+echo -e "\nStarting Kelly..."
+/opt/kelly/bin/kelly start
+sleep 10
+K=`/opt/kelly/bin/kelly ping`
+if [[ $K != 'pong' ]]; then
+    echo $K
+    echo "FAILED"
+    exit 1
+fi
+echo "SUCCESS"
 
 echo -e "\nStarting Just..."
 /opt/just/bin/just start
