Don't copy empty data

diff --git a/setup/phase-setup-oneapi b/setup/phase-setup-oneapi
--- a/setup/phase-setup-oneapi
+++ b/setup/phase-setup-oneapi
@@ -33,11 +33,11 @@ if [[ $? -eq 1 ]]; then
         exit 1
     fi
 
-    cp -r -u data/* $DATA_DIR/oneapi_srv/data
-    if [[ $? -ne 0 ]]; then
-        echo Failed to copy oneapi_srv data
-        exit 1
-    fi
+    #cp -r -u data/* $DATA_DIR/oneapi_srv/data
+    #if [[ $? -ne 0 ]]; then
+    #    echo Failed to copy oneapi_srv data
+    #    exit 1
+    #fi
 
     cp -r -u log/* $LOG_DIR/oneapi_srv
     if [[ $? -ne 0 ]]; then
